# config.yml
# Lista de fontes EPG. Cada entrada: name, url, type.
# type: xml (XMLTV raw) ou json (formato JSON simples descrito abaixo).
# Para json, o script tenta converter para XMLTV.
#
# Exemplos:
# - fontes XMLTV (por exemplo: http://example.com/epg.xml)
# - fontes JSON (estrutura simples: programs: [{channel, start, stop, title, desc}])

sources:
  - name: exemplo-xml
    url: "https://example.com/epg.xml"
    type: xml

  - name: exemplo-json
    url: "https://example.com/epg.json"
    type: json

output_file: "epg.xml"
